### ISSUE TITLE
Make the WebApp responsive

### ISSUE THREAD

**Issue by Radon333** [Radon333/todo-app#1]
Add necessary CSS code to make the Web-App responsive for smaller screens

**Comment by Evavic44** [comment]
Lemme get a free green square. 🏃🏾‍♂️

**Comment by Radon333** [comment]
> Lemme get a free green square. 🏃🏾‍♂️

I'll assign this to you

**Comment by khadijagardezi** [comment]
Can I work on its responsiveness and toggle mode?

**Comment by Evavic44** [comment]
> Can I work on its responsiveness and toggle mode?

@Radon333 sorry but can you assign @khadijagardezi instead to fix this? I'm kind of choked up for now. Sorry about that.

**Comment by Radon333** [comment]
> Can I work on its responsiveness and toggle mode?

assigned

**Comment by Radon333** [comment]
@khadijagardezi what's the progress?

**Comment by Naufal2511** [comment]
Can I try to work on this, Please

**Comment by Radon333** [comment]
@Naufal2511 assigned

**Comment by Naufal2511** [comment]
Thank You for this opportunity, I will reach out to you within next month with my progress

**Comment by Arshdeep-0509** [comment]
hello I would love to work on this

**Comment by Radon333** [comment]
naufal25111 is working on this if he's not able to you can do it 

> hello I would love to work on this
