### ISSUE TITLE
Improve readme.md file.

### ISSUE THREAD

**Issue by Radon333** [Radon333/todo-app#2]
Improve the readme file by adding a brief description on the webapp.

Features
- Add task
- Complete task
- Edit task
- Delete task

Add images or gifs.

**Comment by kumarharsh2396** [comment]
I want to work on this can you assign me.

**Comment by Radon333** [comment]
> I want to work on this can you assign me.

Yes, assigned

**Comment by adityaraute** [comment]
@kumarharsh2396 What's the progress?

**Comment by Radon333** [comment]
> @kumarharsh2396 What's the progress?

if you wish to do it ill assign it to you since I think @kumarharsh2396 isn't working on this
